create_project finn_vivado_stitch_proj /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/vivado_stitch_proj_6n73lbgb -part xc7z020clg400-1
set_property ip_repo_paths [list /workspace/finn/finn-rtllib/memstream /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_0_5zq0wcy6/project_StreamingDataflowPartition_1_StreamingFIFO_0/sol1/impl/verilog /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_Thresholding_Batch_0_7xvapk4_/project_StreamingDataflowPartition_1_Thresholding_Batch_0/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_0_m8tou0py/project_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_0/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_0_4ndc7jjk/project_StreamingDataflowPartition_1_ConvolutionInputGenerator_0/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_1_qwjzzylc/project_StreamingDataflowPartition_1_StreamingFIFO_1/sol1/impl/verilog /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_0_kid44056/project_StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_1_qts7t79b/project_StreamingDataflowPartition_1_ConvolutionInputGenerator_1/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_2_n2ymv40f/project_StreamingDataflowPartition_1_StreamingFIFO_2/sol1/impl/verilog /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_1_rlyb3f5l/project_StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_1_w_6q1cte/project_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_1/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingMaxPool_Batch_0_4zgjpahz/project_StreamingDataflowPartition_1_StreamingMaxPool_Batch_0/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_2_635gk5g4/project_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_2/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_2_0yy6di7f/project_StreamingDataflowPartition_1_ConvolutionInputGenerator_2/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_3_uz33nb69/project_StreamingDataflowPartition_1_StreamingFIFO_3/sol1/impl/verilog /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_2_vsby_qo2/project_StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_3_4e8djtfd/project_StreamingDataflowPartition_1_ConvolutionInputGenerator_3/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_4_c21nvyhq/project_StreamingDataflowPartition_1_StreamingFIFO_4/sol1/impl/verilog /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_3__u8l5m1b/project_StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_3_va9os8f4/project_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_3/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingMaxPool_Batch_1_z6dif_eo/project_StreamingDataflowPartition_1_StreamingMaxPool_Batch_1/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_4_7rqfe8ft/project_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_4/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_4_l06dkrzz/project_StreamingDataflowPartition_1_ConvolutionInputGenerator_4/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_5_t71yrlf9/project_StreamingDataflowPartition_1_StreamingFIFO_5/sol1/impl/verilog /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_4_t3s34udo/project_StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_5_x2smvdcx/project_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_5/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_5_ytvby1y8/project_StreamingDataflowPartition_1_ConvolutionInputGenerator_5/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_5_xarv85n1/project_StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_6__9mykkzg/project_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_6/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_6_dl_v0rnd/project_StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_7_weslpx0e/project_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_7/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_6_irg7szyu/project_StreamingDataflowPartition_1_StreamingFIFO_6/sol1/impl/verilog /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_7_xs5d2uis/project_StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_7_jcc1haew/project_StreamingDataflowPartition_1_StreamingFIFO_7/sol1/impl/verilog /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_8_pti02s77/project_StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_8__6j3kz6o/project_StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_8/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_LabelSelect_Batch_0_hqihul4w/project_StreamingDataflowPartition_1_LabelSelect_Batch_0/sol1/impl/ip /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_8_5zdwu5s5/project_StreamingDataflowPartition_1_StreamingFIFO_8/sol1/impl/verilog] [current_project]
update_ip_catalog
create_bd_design "StreamingDataflowPartition_1"
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFIFO_0:1.0 StreamingDataflowPartition_1_StreamingFIFO_0
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_Thresholding_Batch_0:1.0 StreamingDataflowPartition_1_Thresholding_Batch_0
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_0:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_0
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_ConvolutionInputGenerator_0:1.0 StreamingDataflowPartition_1_ConvolutionInputGenerator_0
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFIFO_1:1.0 StreamingDataflowPartition_1_StreamingFIFO_1
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_0
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFCLayer_Batch_0:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {36} CONFIG.MEM_WIDTH {48} CONFIG.MEM_INIT {/mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_0_kid44056/} CONFIG.RAM_STYLE {auto} CONFIG.STRM0_DEPTH {36} CONFIG.STRM0_WIDTH {48} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_ConvolutionInputGenerator_1:1.0 StreamingDataflowPartition_1_ConvolutionInputGenerator_1
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFIFO_2:1.0 StreamingDataflowPartition_1_StreamingFIFO_2
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_1
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFCLayer_Batch_1:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {72} CONFIG.MEM_WIDTH {512} CONFIG.MEM_INIT {/mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_1_rlyb3f5l/} CONFIG.RAM_STYLE {auto} CONFIG.STRM0_DEPTH {72} CONFIG.STRM0_WIDTH {512} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_1:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_1
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingMaxPool_Batch_0:1.0 StreamingDataflowPartition_1_StreamingMaxPool_Batch_0
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_2:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_2
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_ConvolutionInputGenerator_2:1.0 StreamingDataflowPartition_1_ConvolutionInputGenerator_2
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFIFO_3:1.0 StreamingDataflowPartition_1_StreamingFIFO_3
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_2
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFCLayer_Batch_2:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {288} CONFIG.MEM_WIDTH {256} CONFIG.MEM_INIT {/mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_2_vsby_qo2/} CONFIG.RAM_STYLE {auto} CONFIG.STRM0_DEPTH {288} CONFIG.STRM0_WIDTH {256} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_ConvolutionInputGenerator_3:1.0 StreamingDataflowPartition_1_ConvolutionInputGenerator_3
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFIFO_4:1.0 StreamingDataflowPartition_1_StreamingFIFO_4
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_3
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFCLayer_Batch_3:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {576} CONFIG.MEM_WIDTH {256} CONFIG.MEM_INIT {/mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_3__u8l5m1b/} CONFIG.RAM_STYLE {auto} CONFIG.STRM0_DEPTH {576} CONFIG.STRM0_WIDTH {256} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_3:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_3
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingMaxPool_Batch_1:1.0 StreamingDataflowPartition_1_StreamingMaxPool_Batch_1
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_4:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_4
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_ConvolutionInputGenerator_4:1.0 StreamingDataflowPartition_1_ConvolutionInputGenerator_4
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFIFO_5:1.0 StreamingDataflowPartition_1_StreamingFIFO_5
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_4
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFCLayer_Batch_4:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {4608} CONFIG.MEM_WIDTH {64} CONFIG.MEM_INIT {/mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_4_t3s34udo/} CONFIG.RAM_STYLE {auto} CONFIG.STRM0_DEPTH {4608} CONFIG.STRM0_WIDTH {64} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_5:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_5
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_ConvolutionInputGenerator_5:1.0 StreamingDataflowPartition_1_ConvolutionInputGenerator_5
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_5
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFCLayer_Batch_5:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {36864} CONFIG.MEM_WIDTH {16} CONFIG.MEM_INIT {/mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_5_xarv85n1/} CONFIG.RAM_STYLE {auto} CONFIG.STRM0_DEPTH {36864} CONFIG.STRM0_WIDTH {16} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_6:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_6
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_6
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFCLayer_Batch_6:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {32768} CONFIG.MEM_WIDTH {8} CONFIG.MEM_INIT {/mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_6_dl_v0rnd/} CONFIG.RAM_STYLE {auto} CONFIG.STRM0_DEPTH {32768} CONFIG.STRM0_WIDTH {8} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_7:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_7
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFIFO_6:1.0 StreamingDataflowPartition_1_StreamingFIFO_6
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_7
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFCLayer_Batch_7:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {32768} CONFIG.MEM_WIDTH {8} CONFIG.MEM_INIT {/mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_7_xs5d2uis/} CONFIG.RAM_STYLE {auto} CONFIG.STRM0_DEPTH {32768} CONFIG.STRM0_WIDTH {8} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFIFO_7:1.0 StreamingDataflowPartition_1_StreamingFIFO_7
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_8
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFCLayer_Batch_8:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {1024} CONFIG.MEM_WIDTH {8} CONFIG.MEM_INIT {/mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFCLayer_Batch_8_pti02s77/} CONFIG.RAM_STYLE {auto} CONFIG.STRM0_DEPTH {1024} CONFIG.STRM0_WIDTH {8} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_8:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_8
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_LabelSelect_Batch_0:1.0 StreamingDataflowPartition_1_LabelSelect_Batch_0
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFIFO_8:1.0 StreamingDataflowPartition_1_StreamingFIFO_8
make_bd_pins_external [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_0/ap_clk]
set_property name ap_clk [get_bd_ports ap_clk_0]
make_bd_pins_external [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_0/ap_rst_n]
set_property name ap_rst_n [get_bd_ports ap_rst_n_0]
make_bd_intf_pins_external [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_0/in0_V_V]
set_property name s_axis_0 [get_bd_intf_ports in0_V_V_0]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_Thresholding_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_Thresholding_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_Thresholding_Batch_0/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_Thresholding_Batch_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_0/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_0/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_1/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_1/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_1/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_1/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_2/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_2/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_1/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_1/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_0/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_2/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_2/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_2/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_2/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_3/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_3/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_3/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_3/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_4/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_4/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_3/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_3/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_1/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_1/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_4/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_4/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_4/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_4/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_5/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_5/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_5/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_5/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_5/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_5/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_6/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_6/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_7/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_7/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_7/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_6/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_6/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_7/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_7/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_7/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_8/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_8/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_8/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_LabelSelect_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_LabelSelect_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_8/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_LabelSelect_Batch_0/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_8/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_8/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_LabelSelect_Batch_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_8/in0_V_V]
make_bd_intf_pins_external [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_8/out_V_V]
set_property name m_axis_0 [get_bd_intf_ports out_V_V_0]
set_property CONFIG.FREQ_HZ 100000000.000000 [get_bd_ports /ap_clk]
regenerate_bd_layout
validate_bd_design
save_bd_design
make_wrapper -files [get_files /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/vivado_stitch_proj_6n73lbgb/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_1/StreamingDataflowPartition_1.bd] -top
add_files -norecurse /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/vivado_stitch_proj_6n73lbgb/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_1/hdl/StreamingDataflowPartition_1_wrapper.v
ipx::package_project -root_dir /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/vivado_stitch_proj_6n73lbgb/ip -vendor xilinx_finn -library finn -taxonomy /UserIP -module StreamingDataflowPartition_1 -import_files
set_property core_revision 2 [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
ipx::create_xgui_files [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
set_property value_resolve_type user [ipx::get_bus_parameters -of [ipx::get_bus_interfaces -of [ipx::current_core ]]]
ipx::update_checksums [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
ipx::save_core [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
set all_v_files [get_files -filter {FILE_TYPE == Verilog && USED_IN_SYNTHESIS == 1} ]
set fp [open /mnt/HLSNAS/nthu02/FINN_vision/finn/build/dir/vivado_stitch_proj_6n73lbgb/all_verilog_srcs.txt w]
foreach vf $all_v_files {puts $fp $vf}
close $fp
