-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity aaa is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    a_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    a_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    a_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    a_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    a_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    a_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    a_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    a_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    a_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    a_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    a_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    r_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    r_0_ap_vld : OUT STD_LOGIC;
    r_1_i : IN STD_LOGIC_VECTOR (31 downto 0);
    r_1_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    r_1_o_ap_vld : OUT STD_LOGIC;
    r_2_i : IN STD_LOGIC_VECTOR (31 downto 0);
    r_2_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    r_2_o_ap_vld : OUT STD_LOGIC;
    r_3_i : IN STD_LOGIC_VECTOR (31 downto 0);
    r_3_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    r_3_o_ap_vld : OUT STD_LOGIC;
    r_4_i : IN STD_LOGIC_VECTOR (31 downto 0);
    r_4_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    r_4_o_ap_vld : OUT STD_LOGIC;
    r_5_i : IN STD_LOGIC_VECTOR (31 downto 0);
    r_5_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    r_5_o_ap_vld : OUT STD_LOGIC;
    r_6_i : IN STD_LOGIC_VECTOR (31 downto 0);
    r_6_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    r_6_o_ap_vld : OUT STD_LOGIC;
    r_7_i : IN STD_LOGIC_VECTOR (31 downto 0);
    r_7_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    r_7_o_ap_vld : OUT STD_LOGIC;
    r_8_i : IN STD_LOGIC_VECTOR (31 downto 0);
    r_8_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    r_8_o_ap_vld : OUT STD_LOGIC;
    r_9_i : IN STD_LOGIC_VECTOR (31 downto 0);
    r_9_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    r_9_o_ap_vld : OUT STD_LOGIC;
    r_10_i : IN STD_LOGIC_VECTOR (31 downto 0);
    r_10_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    r_10_o_ap_vld : OUT STD_LOGIC;
    r_11 : OUT STD_LOGIC_VECTOR (31 downto 0);
    r_11_ap_vld : OUT STD_LOGIC );
end;


architecture behav of aaa is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "aaa_aaa,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.763000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=647,HLS_SYN_LUT=2679,HLS_VERSION=2020_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal add_ln14_4_fu_482_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_4_reg_884 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_9_fu_512_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_9_reg_889 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_14_fu_542_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_14_reg_894 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_19_fu_572_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_19_reg_899 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_24_fu_602_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_24_reg_904 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_29_fu_632_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_29_reg_909 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_34_fu_662_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_34_reg_914 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_39_fu_692_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_39_reg_919 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_44_fu_722_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_44_reg_924 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_49_fu_752_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_49_reg_929 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_fu_758_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_reg_934 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_2_fu_764_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_2_reg_939 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_4_fu_770_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_4_reg_944 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_6_fu_776_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_6_reg_949 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_8_fu_782_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_8_reg_954 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_10_fu_788_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_10_reg_959 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_12_fu_794_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_12_reg_964 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_14_fu_800_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_14_reg_969 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_16_fu_806_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_16_reg_974 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_18_fu_812_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_18_reg_979 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_mux_i_phi_fu_414_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_reg_410 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln11_fu_878_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln15_15_fu_830_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_19_fu_818_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_13_fu_836_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_17_fu_824_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_11_fu_842_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_9_fu_848_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_7_fu_854_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_5_fu_860_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_1_fu_872_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_fu_458_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_2_fu_470_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_3_fu_476_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_1_fu_464_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_5_fu_488_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_7_fu_500_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_8_fu_506_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_6_fu_494_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_10_fu_518_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_12_fu_530_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_13_fu_536_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_11_fu_524_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_15_fu_548_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_17_fu_560_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_18_fu_566_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_16_fu_554_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_20_fu_578_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_22_fu_590_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_23_fu_596_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_21_fu_584_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_25_fu_608_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_27_fu_620_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_28_fu_626_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_26_fu_614_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_30_fu_638_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_32_fu_650_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_33_fu_656_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_31_fu_644_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_35_fu_668_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_37_fu_680_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_38_fu_686_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_36_fu_674_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_40_fu_698_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_42_fu_710_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_43_fu_716_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_41_fu_704_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_45_fu_728_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_47_fu_740_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_48_fu_746_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln14_46_fu_734_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_condition_182 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_reg_410_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_410 <= ap_const_lv4_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_878_p2 = ap_const_lv1_0))) then 
                i_reg_410 <= ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add_ln14_14_reg_894 <= add_ln14_14_fu_542_p2;
                add_ln14_19_reg_899 <= add_ln14_19_fu_572_p2;
                add_ln14_24_reg_904 <= add_ln14_24_fu_602_p2;
                add_ln14_29_reg_909 <= add_ln14_29_fu_632_p2;
                add_ln14_34_reg_914 <= add_ln14_34_fu_662_p2;
                add_ln14_39_reg_919 <= add_ln14_39_fu_692_p2;
                add_ln14_44_reg_924 <= add_ln14_44_fu_722_p2;
                add_ln14_49_reg_929 <= add_ln14_49_fu_752_p2;
                add_ln14_4_reg_884 <= add_ln14_4_fu_482_p2;
                add_ln14_9_reg_889 <= add_ln14_9_fu_512_p2;
                add_ln15_10_reg_959 <= add_ln15_10_fu_788_p2;
                add_ln15_12_reg_964 <= add_ln15_12_fu_794_p2;
                add_ln15_14_reg_969 <= add_ln15_14_fu_800_p2;
                add_ln15_16_reg_974 <= add_ln15_16_fu_806_p2;
                add_ln15_18_reg_979 <= add_ln15_18_fu_812_p2;
                add_ln15_2_reg_939 <= add_ln15_2_fu_764_p2;
                add_ln15_4_reg_944 <= add_ln15_4_fu_770_p2;
                add_ln15_6_reg_949 <= add_ln15_6_fu_776_p2;
                add_ln15_8_reg_954 <= add_ln15_8_fu_782_p2;
                add_ln15_reg_934 <= add_ln15_fu_758_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln11_fu_878_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_878_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln14_10_fu_518_p2 <= std_logic_vector(unsigned(b_2) + unsigned(a_3));
    add_ln14_11_fu_524_p2 <= std_logic_vector(unsigned(add_ln14_10_fu_518_p2) + unsigned(b_1));
    add_ln14_12_fu_530_p2 <= std_logic_vector(unsigned(a_2) + unsigned(b_3));
    add_ln14_13_fu_536_p2 <= std_logic_vector(unsigned(add_ln14_12_fu_530_p2) + unsigned(a_1));
    add_ln14_14_fu_542_p2 <= std_logic_vector(unsigned(add_ln14_13_fu_536_p2) + unsigned(add_ln14_11_fu_524_p2));
    add_ln14_15_fu_548_p2 <= std_logic_vector(unsigned(b_3) + unsigned(a_4));
    add_ln14_16_fu_554_p2 <= std_logic_vector(unsigned(add_ln14_15_fu_548_p2) + unsigned(b_2));
    add_ln14_17_fu_560_p2 <= std_logic_vector(unsigned(a_3) + unsigned(b_4));
    add_ln14_18_fu_566_p2 <= std_logic_vector(unsigned(add_ln14_17_fu_560_p2) + unsigned(a_2));
    add_ln14_19_fu_572_p2 <= std_logic_vector(unsigned(add_ln14_18_fu_566_p2) + unsigned(add_ln14_16_fu_554_p2));
    add_ln14_1_fu_464_p2 <= std_logic_vector(unsigned(add_ln14_fu_458_p2) + unsigned(b_0));
    add_ln14_20_fu_578_p2 <= std_logic_vector(unsigned(b_4) + unsigned(a_5));
    add_ln14_21_fu_584_p2 <= std_logic_vector(unsigned(add_ln14_20_fu_578_p2) + unsigned(b_3));
    add_ln14_22_fu_590_p2 <= std_logic_vector(unsigned(a_4) + unsigned(b_5));
    add_ln14_23_fu_596_p2 <= std_logic_vector(unsigned(add_ln14_22_fu_590_p2) + unsigned(a_3));
    add_ln14_24_fu_602_p2 <= std_logic_vector(unsigned(add_ln14_23_fu_596_p2) + unsigned(add_ln14_21_fu_584_p2));
    add_ln14_25_fu_608_p2 <= std_logic_vector(unsigned(b_5) + unsigned(a_6));
    add_ln14_26_fu_614_p2 <= std_logic_vector(unsigned(add_ln14_25_fu_608_p2) + unsigned(b_4));
    add_ln14_27_fu_620_p2 <= std_logic_vector(unsigned(a_5) + unsigned(b_6));
    add_ln14_28_fu_626_p2 <= std_logic_vector(unsigned(add_ln14_27_fu_620_p2) + unsigned(a_4));
    add_ln14_29_fu_632_p2 <= std_logic_vector(unsigned(add_ln14_28_fu_626_p2) + unsigned(add_ln14_26_fu_614_p2));
    add_ln14_2_fu_470_p2 <= std_logic_vector(unsigned(a_1) + unsigned(b_2));
    add_ln14_30_fu_638_p2 <= std_logic_vector(unsigned(b_6) + unsigned(a_7));
    add_ln14_31_fu_644_p2 <= std_logic_vector(unsigned(add_ln14_30_fu_638_p2) + unsigned(b_5));
    add_ln14_32_fu_650_p2 <= std_logic_vector(unsigned(a_6) + unsigned(b_7));
    add_ln14_33_fu_656_p2 <= std_logic_vector(unsigned(add_ln14_32_fu_650_p2) + unsigned(a_5));
    add_ln14_34_fu_662_p2 <= std_logic_vector(unsigned(add_ln14_33_fu_656_p2) + unsigned(add_ln14_31_fu_644_p2));
    add_ln14_35_fu_668_p2 <= std_logic_vector(unsigned(b_7) + unsigned(a_8));
    add_ln14_36_fu_674_p2 <= std_logic_vector(unsigned(add_ln14_35_fu_668_p2) + unsigned(b_6));
    add_ln14_37_fu_680_p2 <= std_logic_vector(unsigned(a_7) + unsigned(b_8));
    add_ln14_38_fu_686_p2 <= std_logic_vector(unsigned(add_ln14_37_fu_680_p2) + unsigned(a_6));
    add_ln14_39_fu_692_p2 <= std_logic_vector(unsigned(add_ln14_38_fu_686_p2) + unsigned(add_ln14_36_fu_674_p2));
    add_ln14_3_fu_476_p2 <= std_logic_vector(unsigned(add_ln14_2_fu_470_p2) + unsigned(a_0));
    add_ln14_40_fu_698_p2 <= std_logic_vector(unsigned(b_8) + unsigned(a_9));
    add_ln14_41_fu_704_p2 <= std_logic_vector(unsigned(add_ln14_40_fu_698_p2) + unsigned(b_7));
    add_ln14_42_fu_710_p2 <= std_logic_vector(unsigned(a_8) + unsigned(b_9));
    add_ln14_43_fu_716_p2 <= std_logic_vector(unsigned(add_ln14_42_fu_710_p2) + unsigned(a_7));
    add_ln14_44_fu_722_p2 <= std_logic_vector(unsigned(add_ln14_43_fu_716_p2) + unsigned(add_ln14_41_fu_704_p2));
    add_ln14_45_fu_728_p2 <= std_logic_vector(unsigned(b_9) + unsigned(a_10));
    add_ln14_46_fu_734_p2 <= std_logic_vector(unsigned(add_ln14_45_fu_728_p2) + unsigned(b_8));
    add_ln14_47_fu_740_p2 <= std_logic_vector(unsigned(a_9) + unsigned(b_10));
    add_ln14_48_fu_746_p2 <= std_logic_vector(unsigned(add_ln14_47_fu_740_p2) + unsigned(a_8));
    add_ln14_49_fu_752_p2 <= std_logic_vector(unsigned(add_ln14_48_fu_746_p2) + unsigned(add_ln14_46_fu_734_p2));
    add_ln14_4_fu_482_p2 <= std_logic_vector(unsigned(add_ln14_3_fu_476_p2) + unsigned(add_ln14_1_fu_464_p2));
    add_ln14_5_fu_488_p2 <= std_logic_vector(unsigned(b_10) + unsigned(a_11));
    add_ln14_6_fu_494_p2 <= std_logic_vector(unsigned(add_ln14_5_fu_488_p2) + unsigned(b_9));
    add_ln14_7_fu_500_p2 <= std_logic_vector(unsigned(a_10) + unsigned(b_11));
    add_ln14_8_fu_506_p2 <= std_logic_vector(unsigned(add_ln14_7_fu_500_p2) + unsigned(a_9));
    add_ln14_9_fu_512_p2 <= std_logic_vector(unsigned(add_ln14_8_fu_506_p2) + unsigned(add_ln14_6_fu_494_p2));
    add_ln14_fu_458_p2 <= std_logic_vector(unsigned(b_1) + unsigned(a_2));
    add_ln15_10_fu_788_p2 <= std_logic_vector(unsigned(add_ln14_29_fu_632_p2) + unsigned(ap_const_lv32_1));
    add_ln15_11_fu_842_p2 <= std_logic_vector(unsigned(add_ln15_10_reg_959) + unsigned(r_5_i));
    add_ln15_12_fu_794_p2 <= std_logic_vector(unsigned(add_ln14_34_fu_662_p2) + unsigned(ap_const_lv32_1));
    add_ln15_13_fu_836_p2 <= std_logic_vector(unsigned(add_ln15_12_reg_964) + unsigned(r_6_i));
    add_ln15_14_fu_800_p2 <= std_logic_vector(unsigned(add_ln14_39_fu_692_p2) + unsigned(ap_const_lv32_1));
    add_ln15_15_fu_830_p2 <= std_logic_vector(unsigned(add_ln15_14_reg_969) + unsigned(r_7_i));
    add_ln15_16_fu_806_p2 <= std_logic_vector(unsigned(add_ln14_44_fu_722_p2) + unsigned(ap_const_lv32_1));
    add_ln15_17_fu_824_p2 <= std_logic_vector(unsigned(add_ln15_16_reg_974) + unsigned(r_8_i));
    add_ln15_18_fu_812_p2 <= std_logic_vector(unsigned(add_ln14_49_fu_752_p2) + unsigned(ap_const_lv32_1));
    add_ln15_19_fu_818_p2 <= std_logic_vector(unsigned(add_ln15_18_reg_979) + unsigned(r_9_i));
    add_ln15_1_fu_872_p2 <= std_logic_vector(unsigned(add_ln15_reg_934) + unsigned(r_1_i));
    add_ln15_2_fu_764_p2 <= std_logic_vector(unsigned(add_ln14_9_fu_512_p2) + unsigned(ap_const_lv32_1));
    add_ln15_4_fu_770_p2 <= std_logic_vector(unsigned(add_ln14_14_fu_542_p2) + unsigned(ap_const_lv32_1));
    add_ln15_5_fu_860_p2 <= std_logic_vector(unsigned(add_ln15_4_reg_944) + unsigned(r_2_i));
    add_ln15_6_fu_776_p2 <= std_logic_vector(unsigned(add_ln14_19_fu_572_p2) + unsigned(ap_const_lv32_1));
    add_ln15_7_fu_854_p2 <= std_logic_vector(unsigned(add_ln15_6_reg_949) + unsigned(r_3_i));
    add_ln15_8_fu_782_p2 <= std_logic_vector(unsigned(add_ln14_24_fu_602_p2) + unsigned(ap_const_lv32_1));
    add_ln15_9_fu_848_p2 <= std_logic_vector(unsigned(add_ln15_8_reg_954) + unsigned(r_4_i));
    add_ln15_fu_758_p2 <= std_logic_vector(unsigned(add_ln14_4_fu_482_p2) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_condition_182_assign_proc : process(ap_phi_mux_i_phi_fu_414_p4)
    begin
                ap_condition_182 <= ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_0) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_A) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_B) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_C) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_D) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_E) or (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_F)))))));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_mux_i_phi_fu_414_p4 <= i_reg_410;

    ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20_assign_proc : process(ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2, ap_condition_182)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_const_boolean_1 = ap_condition_182)) then 
                ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20 <= ap_const_lv4_1;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_1)) then 
                ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20 <= ap_const_lv4_2;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_2)) then 
                ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20 <= ap_const_lv4_3;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_3)) then 
                ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20 <= ap_const_lv4_4;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_4)) then 
                ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20 <= ap_const_lv4_5;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_5)) then 
                ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20 <= ap_const_lv4_6;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_6)) then 
                ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20 <= ap_const_lv4_7;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_7)) then 
                ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20 <= ap_const_lv4_8;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_8)) then 
                ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20 <= ap_const_lv4_9;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_9)) then 
                ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20 <= ap_const_lv4_A;
            else 
                ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20 <= "XXXX";
            end if;
        else 
            ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20 <= "XXXX";
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln11_fu_878_p2 <= "1" when (ap_phi_mux_indvars_iv_next2070107144181219247_phi_fu_425_p20 = ap_const_lv4_A) else "0";
    r_0 <= add_ln14_4_reg_884;

    r_0_ap_vld_assign_proc : process(ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_0) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_A) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_B) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_C) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_D) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_E) or (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_F))))))))) then 
            r_0_ap_vld <= ap_const_logic_1;
        else 
            r_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    r_10_o_assign_proc : process(r_10_i, ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2, add_ln15_19_fu_818_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_8))) then 
            r_10_o <= add_ln15_19_fu_818_p2;
        else 
            r_10_o <= r_10_i;
        end if; 
    end process;


    r_10_o_ap_vld_assign_proc : process(ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_8))) then 
            r_10_o_ap_vld <= ap_const_logic_1;
        else 
            r_10_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    r_11 <= std_logic_vector(unsigned(add_ln15_2_reg_939) + unsigned(r_10_i));

    r_11_ap_vld_assign_proc : process(ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_9))) then 
            r_11_ap_vld <= ap_const_logic_1;
        else 
            r_11_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    r_1_o_assign_proc : process(r_1_i, add_ln14_14_reg_894, ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_1))) then 
            r_1_o <= add_ln14_14_reg_894;
        else 
            r_1_o <= r_1_i;
        end if; 
    end process;


    r_1_o_ap_vld_assign_proc : process(ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_1))) then 
            r_1_o_ap_vld <= ap_const_logic_1;
        else 
            r_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    r_2_o_assign_proc : process(r_2_i, add_ln14_19_reg_899, ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2, add_ln15_1_fu_872_p2, ap_condition_182)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_const_boolean_1 = ap_condition_182)) then 
                r_2_o <= add_ln15_1_fu_872_p2;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_2)) then 
                r_2_o <= add_ln14_19_reg_899;
            else 
                r_2_o <= r_2_i;
            end if;
        else 
            r_2_o <= r_2_i;
        end if; 
    end process;


    r_2_o_ap_vld_assign_proc : process(ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_0) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_A) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_B) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_C) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_D) or ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_E) or (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_F)))))))) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_2)))) then 
            r_2_o_ap_vld <= ap_const_logic_1;
        else 
            r_2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    r_3_o_assign_proc : process(r_3_i, add_ln14_24_reg_904, ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2, add_ln15_5_fu_860_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_1)) then 
                r_3_o <= add_ln15_5_fu_860_p2;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_3)) then 
                r_3_o <= add_ln14_24_reg_904;
            else 
                r_3_o <= r_3_i;
            end if;
        else 
            r_3_o <= r_3_i;
        end if; 
    end process;


    r_3_o_ap_vld_assign_proc : process(ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_3)))) then 
            r_3_o_ap_vld <= ap_const_logic_1;
        else 
            r_3_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    r_4_o_assign_proc : process(r_4_i, add_ln14_29_reg_909, ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2, add_ln15_7_fu_854_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_2)) then 
                r_4_o <= add_ln15_7_fu_854_p2;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_4)) then 
                r_4_o <= add_ln14_29_reg_909;
            else 
                r_4_o <= r_4_i;
            end if;
        else 
            r_4_o <= r_4_i;
        end if; 
    end process;


    r_4_o_ap_vld_assign_proc : process(ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_2)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_4)))) then 
            r_4_o_ap_vld <= ap_const_logic_1;
        else 
            r_4_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    r_5_o_assign_proc : process(r_5_i, add_ln14_34_reg_914, ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2, add_ln15_9_fu_848_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_3)) then 
                r_5_o <= add_ln15_9_fu_848_p2;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_5)) then 
                r_5_o <= add_ln14_34_reg_914;
            else 
                r_5_o <= r_5_i;
            end if;
        else 
            r_5_o <= r_5_i;
        end if; 
    end process;


    r_5_o_ap_vld_assign_proc : process(ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_3)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_5)))) then 
            r_5_o_ap_vld <= ap_const_logic_1;
        else 
            r_5_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    r_6_o_assign_proc : process(r_6_i, add_ln14_39_reg_919, ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2, add_ln15_11_fu_842_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_4)) then 
                r_6_o <= add_ln15_11_fu_842_p2;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_6)) then 
                r_6_o <= add_ln14_39_reg_919;
            else 
                r_6_o <= r_6_i;
            end if;
        else 
            r_6_o <= r_6_i;
        end if; 
    end process;


    r_6_o_ap_vld_assign_proc : process(ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_4)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_6)))) then 
            r_6_o_ap_vld <= ap_const_logic_1;
        else 
            r_6_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    r_7_o_assign_proc : process(r_7_i, add_ln14_44_reg_924, ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2, add_ln15_13_fu_836_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_5)) then 
                r_7_o <= add_ln15_13_fu_836_p2;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_7)) then 
                r_7_o <= add_ln14_44_reg_924;
            else 
                r_7_o <= r_7_i;
            end if;
        else 
            r_7_o <= r_7_i;
        end if; 
    end process;


    r_7_o_ap_vld_assign_proc : process(ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_5)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_7)))) then 
            r_7_o_ap_vld <= ap_const_logic_1;
        else 
            r_7_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    r_8_o_assign_proc : process(r_8_i, add_ln14_49_reg_929, ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2, add_ln15_15_fu_830_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_6)) then 
                r_8_o <= add_ln15_15_fu_830_p2;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_8)) then 
                r_8_o <= add_ln14_49_reg_929;
            else 
                r_8_o <= r_8_i;
            end if;
        else 
            r_8_o <= r_8_i;
        end if; 
    end process;


    r_8_o_ap_vld_assign_proc : process(ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_6)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_8)))) then 
            r_8_o_ap_vld <= ap_const_logic_1;
        else 
            r_8_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    r_9_o_assign_proc : process(r_9_i, add_ln14_9_reg_889, ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2, add_ln15_17_fu_824_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_9)) then 
                r_9_o <= add_ln14_9_reg_889;
            elsif ((ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_7)) then 
                r_9_o <= add_ln15_17_fu_824_p2;
            else 
                r_9_o <= r_9_i;
            end if;
        else 
            r_9_o <= r_9_i;
        end if; 
    end process;


    r_9_o_ap_vld_assign_proc : process(ap_phi_mux_i_phi_fu_414_p4, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_7)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_phi_mux_i_phi_fu_414_p4 = ap_const_lv4_9)))) then 
            r_9_o_ap_vld <= ap_const_logic_1;
        else 
            r_9_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
