// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern "C" void AESL_WRAP_aaa (
volatile void* a_0,
volatile void* a_1,
volatile void* a_2,
volatile void* a_3,
volatile void* a_4,
volatile void* a_5,
volatile void* a_6,
volatile void* a_7,
volatile void* a_8,
volatile void* a_9,
volatile void* a_10,
volatile void* a_11,
volatile void* b_0,
volatile void* b_1,
volatile void* b_2,
volatile void* b_3,
volatile void* b_4,
volatile void* b_5,
volatile void* b_6,
volatile void* b_7,
volatile void* b_8,
volatile void* b_9,
volatile void* b_10,
volatile void* b_11,
volatile void* r_0,
volatile void* r_1,
volatile void* r_2,
volatile void* r_3,
volatile void* r_4,
volatile void* r_5,
volatile void* r_6,
volatile void* r_7,
volatile void* r_8,
volatile void* r_9,
volatile void* r_10,
volatile void* r_11);
